#!/usr/bin/env bash
# Print a Markdown environment snapshot to stdout. Read-only; prints no secrets.
#   scripts/check_environment.sh > docs/environment_snapshot.md
set -uo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HACK="$(dirname "$REPO")"

section() { printf '\n## %s\n\n```\n' "$1"; }
endsec() { printf '```\n'; }
run() { "$@" 2>&1 || true; }
have() { command -v "$1" >/dev/null 2>&1; }
# Strip any credentials embedded in remote URLs (https://user:token@host).
scrub() { sed -E 's#(https?://)[^/@[:space:]]+@#\1<redacted>@#g'; }

main() {
echo "# VoxelTrace environment snapshot"
echo
echo "Generated by \`scripts/check_environment.sh\`. No secrets are recorded."

section "Date / host"
echo "date:      $(date -Is)"
echo "hostname:  $(hostname)"
endsec

section "OS"
run grep -E '^(PRETTY_NAME|VERSION_ID)=' /etc/os-release
echo "uname -a:  $(uname -a)"
echo "arch:      $(uname -m)"
endsec

section "CPU"
run lscpu | grep -E '^(Architecture|CPU\(s\)|Vendor ID|Model name|Core\(s\) per socket|CPU max MHz)'
endsec

section "Memory"
run free -h
endsec

section "Disk (/home/dell)"
run df -h /home/dell
endsec

section "Python"
for p in python3 python3.11 python3.12 python3.13; do
  have "$p" && echo "$p: $($p --version 2>&1) ($(command -v "$p"))"
done
have python3 && echo "system pip: $(python3 -m pip --version 2>&1)"
if [ -x "$REPO/.venv/bin/python" ]; then
  echo "project venv: $("$REPO/.venv/bin/python" --version) ($REPO/.venv)"
  echo "venv pip:     $("$REPO/.venv/bin/pip" --version)"
fi
endsec

section "Tools"
echo "git:         $(run git --version)"
echo "claude code: $(have claude && run claude --version || echo 'not found')"
if have gh; then
  echo "gh:          $(gh --version | head -1)"
  if gh auth status >/dev/null 2>&1; then echo "gh auth:     authenticated"; else echo "gh auth:     NOT authenticated"; fi
else
  echo "gh:          not installed"
fi
endsec

section "NVIDIA driver / CUDA"
run cat /proc/driver/nvidia/version
have nvcc && run nvcc --version | tail -2
endsec

section "nvidia-smi"
if have nvidia-smi; then run nvidia-smi; else echo "nvidia-smi not found"; fi
endsec

section "Docker"
if have docker; then
  echo "version: $(run docker --version)"
  if docker info >/dev/null 2>&1; then echo "daemon:  accessible to $(whoami)"
  else echo "daemon:  NOT accessible to $(whoami) (permission or daemon issue)"; fi
else
  echo "docker not installed"
fi
endsec

section "Git"
echo "branch:  $(git -C "$REPO" branch --show-current)"
echo "commit:  $(git -C "$REPO" rev-parse HEAD 2>/dev/null || echo none)"
echo "remotes:"
git -C "$REPO" remote -v | scrub
[ -z "$(git -C "$REPO" remote)" ] && echo "  (none)"
endsec

section "Project tree"
echo "root: $HACK"
run ls -1 "$HACK"
endsec
}

# Strip trailing whitespace (nvidia-smi pads its table) so the snapshot passes git diff --check.
main | sed -E 's/[[:space:]]+$//'
