#!/usr/bin/env python3
"""Reason-code -> test coverage matrix (writes docs/failure_injection_coverage.md).

A code counts as covered when a test file names it literally. Codes that no source module
emits are CATALOG_ONLY; pixel-stage defensive guards that cannot be reached from valid
header-only fixtures are GUARD_ONLY (listed, not counted as gaps).
"""

from __future__ import annotations

import re
from pathlib import Path

from voxeltrace.preflight.reasons import CATALOG as PREFLIGHT
from voxeltrace.trial.drift import EVENT_FOR_FIELD
from voxeltrace.trial.reasons import CATALOG as TRIAL

REPO = Path(__file__).resolve().parents[1]
GUARD_ONLY = {
    "PIXELS_NOT_LOADED",
    "NONFINITE_SUV",
    "RESCALE_AUDIT_MISMATCH",
    "NEGATIVE_SUV",
    "GEOMETRY",
}
SCENARIOS = {
    "missing weight": ("test_preflight.py", "test_missing_weight_is_blocking"),
    "missing height": ("test_preflight.py", "MISSING_PATIENTSIZE"),
    "invalid dose": ("test_census_v2.py / test_suv*", "IMPLAUSIBLE_RADIONUCLIDETOTALDOSE"),
    "missing half-life": ("test_suv*", "MISSING_RADIONUCLIDEHALFLIFE"),
    "timing rollover": ("test_suv*", "INJECTION_DATE_ROLLOVER"),
    "DecayFactor mismatch": ("test_preflight.py", "DECAY_FACTOR_INCONSISTENT"),
    "DecayFactor absent": ("test_failure_injection.py", "DECAY_FACTOR_UNVERIFIED"),
    "CT FoR mismatch": ("test_preflight.py", "CT_NOT_IN_PET_FRAME"),
    "reconstruction mismatch": ("test_fingerprint_drift.py", "test_reconstruction_change_is_different_with_rule_impact"),
    "scanner change": ("test_failure_injection.py", "SCANNER_CHANGE"),
    "software change": ("test_fingerprint_drift.py", "SOFTWARE_CHANGE"),
    "filter change": ("test_failure_injection.py", "FILTER_CHANGE"),
    "voxel-size change": ("test_failure_injection.py", "VOXEL_SIZE_CHANGE"),
    "correction mismatch": ("test_failure_injection.py", "CORRECTION_CHANGE"),
    "tracer mismatch": ("test_failure_injection.py", "TRACER_CHANGE"),
    "uptake violation": ("test_trial_rules.py", "test_qiba_uptake_difference"),
    "private-tag stripping": ("test_vendors_anonymization.py", "UNKNOWN_OR_STRIPPED"),
    "stale attestation": ("test_qiba_attestation.py", "test_stale_attestation_not_used"),
    "wrong-series attestation": ("test_qiba_attestation.py", "SERIES_CHANGED"),
    "tampered review": ("test_reference_review.py", "REVIEW_INVALID"),
    "tampered evidence bundle": ("test_pilot_bundle.py", "test_tamper_detection"),
    "human override": ("test_pilot_bundle.py", "OVERRIDDEN_BY_HUMAN"),
    "protocol drift": ("test_fingerprint_drift.py", "test_drift_events_cite_evidence"),
}  # fmt: skip


def main() -> int:
    src = {p: p.read_text() for p in (REPO / "src").rglob("*.py")}
    tests = {p.name: p.read_text() for p in (REPO / "tests").glob("test_*.py")}
    suv = (REPO / "src/voxeltrace/quant/suv.py").read_text()
    families = {
        "strict SUV validator": sorted(set(re.findall(r'"([A-Z][A-Z0-9_]{5,})"', suv)) - {"START", "BQML", "NONE"}),
        "trial reasons": sorted(TRIAL),
        "preflight": sorted(PREFLIGHT),
        "drift events": sorted(set(EVENT_FOR_FIELD.values()) | {"UNKNOWN_PROTOCOL_DRIFT", "UPTAKE_OUTLIER", "DOSE_OUTLIER"}),
    }  # fmt: skip
    lines = ["# Failure-injection coverage (reason code -> tests)", "",
             "Generated by `scripts/reason_coverage.py`. A code is covered when a test names it.",
             "CATALOG_ONLY = defined but never emitted by any source module.",
             "GUARD_ONLY = pixel-stage defensive guard, not reachable from header-only fixtures.", ""]  # fmt: skip
    total = covered = 0
    for fam, codes in families.items():
        lines += [f"## {fam}", "", "| code | status | tests |", "|---|---|---|"]
        for c in codes:
            emitted = any(f'"{c}"' in t for p, t in src.items() if "reasons.py" not in p.name)
            ts = sorted(n for n, t in tests.items() if c in t)
            if not emitted and fam != "strict SUV validator":
                status = "CATALOG_ONLY"
            elif c in GUARD_ONLY and not ts:
                status = "GUARD_ONLY"
            else:
                total += 1
                covered += bool(ts)
                status = "COVERED" if ts else "GAP"
            lines.append(f"| `{c}` | {status} | {', '.join(ts) or '-'} |")
        lines.append("")
    lines += ["## Requested scenarios", "", "| scenario | test |", "|---|---|"]
    lines += [f"| {k} | {f} (`{n}`) |" for k, (f, n) in SCENARIOS.items()]
    lines.insert(6, f"**Emittable codes covered: {covered} / {total}.**\n")
    (REPO / "docs" / "failure_injection_coverage.md").write_text("\n".join(lines) + "\n")
    print(f"covered {covered}/{total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
